### ISSUE TITLE
Publish to Gradle plugin portal

### ISSUE THREAD

**Issue by punya** [palantir/gradle-jacoco-coverage#7]
This project should be published to `plugins.gradle.org` and renamed accordingly.

**Comment by thatsIch** [comment]
For more clarification

Since Gradle 2.1+ you can use

```
plugins {
    id "<your unique ID>"
}
```

It just requires to be in the central plugin repo of Gradle. See https://plugins.gradle.org

**Comment by uschi2000** [comment]
Main reason for not having published to plugins.gradle.org is the lack of fine-grained control over plugin application: If I understand this right, then you cannot not apply the plugin to the root project. So while the plugin mechanism would work fine for single-project builds, the vast majority of our projects are multi-project and the current state of the plugins mechanism is simply not flexible enough. [Unless this has changed since 2.4 or 2.5 when I last looked into it?]

**Comment by thatsIch** [comment]
https://docs.gradle.org/current/userguide/plugins.html

> Future versions of Gradle will remove this restriction.

Apparently this does work with multi projects but currently not with `subproject {}` etc. Anyways, by putting it into the plugins repo, there will be no drawback, since you can still use it like before.

€: nice, just found it via google https://plugins.gradle.org/plugin/com.palantir.jacoco-coverage
was wondering why the dependency could not be resolved. Seems you took down the whole package on JCenter

€€: apparently it is hitting a missing dependency from Guava

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.google.guava:guava:18.0"
    }
}
```

Adding guava to the classpath fixes this

**Comment by vraravam** [comment]
Unable to use your plaugin in a single-project gradle 2.9 scenario. Please help.

**Comment by uschi2000** [comment]
@vraravam you'll have to provide a little more information please.

**Comment by crazy4groovy** [comment]
Similar problem :( I would like to use with `plugins { ... }` single-project:

```
A problem occurred configuring root project 'myproject'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not download jacoco-coverage.jar (gradle.plugin.com.palantir:jacoco-coverage:0.3.0)
      > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/com/palantir/jacoco-coverage/0.3.0/jacoco-coverage-0.3.0.jar'.
```

**Comment by ash211** [comment]
Done?  https://plugins.gradle.org/plugin/com.palantir.jacoco-full-report
